version: '3'
services:
  frontend:
    container_name: frontend
    image: php:7.0-apache
    ports:
      - 80:80
    volumes:
      - ./frontend:/var/www/html
  websocket:
    container_name: backend_websocket
    build: ./backend_websocket
    ports:
      - 8080:8080
  api:
    container_name: backend_api
    build: ./backend_api
    ports:
      - 3000:3000
  
